from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.implicitly_wait(4)

driver.get('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
login = driver.find_element(By.XPATH, '//button[text()="Customer Login"]')
login.click()
select_customer = driver.find_element(By.XPATH, '//select[@id="userSelect"]')
select_customer.click()
select_ron = driver.find_element(By.XPATH, '//option[text()="Ron Weasly"]')
select_ron.click()
select_harry = driver.find_element(By.XPATH, '//option[text()="Harry Potter"]')
select_harry.click()
click_button_login = driver.find_element(By.XPATH, '//button[@class="btn btn-default"]')
click_button_login.click()
put_money = driver.find_element(By.XPATH, '//button[@class="btn btn-lg tab"][2]')
put_money.click()
amount = driver.find_element(By.CSS_SELECTOR, 'input.form-control')
amount.send_keys(100)
click_button_deposit = driver.find_element(By.XPATH, '//button[@class="btn btn-default"]')
click_button_deposit.click()
check_the_amount = driver.find_element(By.XPATH, '//button[@class="btn btn-lg tab"][1]')
check_the_amount.click()
logout = driver.find_element(By.XPATH, '//button[@class="btn logout"]')
logout.click()
driver.quit()
